version: '3.7'

services:
  web_segmentacion:
    image: nginx:stable-alpine3.21-perl
    container_name: web_segmentacion
    restart: always
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red-gane-int

  api_segmentacion:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_segmentacion
    restart: always
    image: api-segmentacion-v1.1
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota
      
networks:
  red-gane-int:
    external: true